# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='ROLLOVER',
            field=models.CharField(choices=[('0', '\u65e0\u7ffb\u8f66/\u7ffb\u8f6c'), ('1', '\u7ffb\u8f66-\u88ab\u7269\u4f53/\u8f66\u8f86\u649e\u7ffb'), ('2', '\u7ffb\u8f66-\u81ea\u8eab\u4f5c\u7528'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='9', help_text='\u8be5\u8f66\u662f\u5426\u7ffb\u8f6c\u6216\u7ffb\u8f66', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='UNDERIDE',
            field=models.CharField(choices=[('0', '\u65e0\u4e0a\u9a91\u4e0b\u94bb'), ('1', '\u4e0b\u94bb-\u8231\u5ba4\u5165\u4fb5'), ('2', '\u4e0b\u94bb-\u65e0\u8231\u5ba4\u5165\u4fb5'), ('3', '\u4e0a\u9a91'), ('4', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='4', help_text='\u8be5\u8f66\u8f86\u662f\u5426\u53d1\u751f\u4e0a\u9a91\u4e0b\u94bb\uff0c\u88ab\u649e\u65f6\u4e0d\u8ba1\u5165\u5728\u5185', max_length=20),
        ),
    ]
