# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0002_auto_20180110_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='BODYTYPE',
            field=models.CharField(choices=[('01', '\u5fae\u578b\u8d27\u8f66'), ('02', '\u8f7b\u578b\u8d27\u8f66'), ('03', '\u4e2d\u578b\u8d27\u8f66'), ('04', '\u4e2d\u578b\u8d27\u8f66'), ('11', '\u8f7b\u578b\u8d8a\u91ce\u8f66'), ('12', '\u4e2d\u578b\u8d8a\u91ce\u8f66'), ('13', '\u91cd\u578b\u8d8a\u91ce\u8f66'), ('14', '\u8d85\u91cd\u578b\u8d8a\u91ce\u8f66'), ('21', '\u8f7b\u578b\u81ea\u5378\u8f66'), ('22', '\u4e2d\u578b\u81ea\u5378\u8f66'), ('23', '\u91cd\u578b\u81ea\u5378\u8f66'), ('24', '\u77ff\u7528\u81ea\u5378\u8f66'), ('31', '\u534a\u6302\u7275\u5f15\u8f66'), ('32', '\u5168\u6302\u7275\u5f15\u8f66'), ('41', '\u7bb1\u5f0f\u6c7d\u8f66'), ('42', '\u7f50\u5f0f\u6c7d\u8f66'), ('43', '\u8d77\u91cd\u4e3e\u5347\u8f66'), ('44', '\u4ed3\u6805\u5f0f\u8f66'), ('45', '\u7279\u79cd\u7ed3\u6784\u8f66'), ('46', '\u4e13\u7528\u81ea\u5378\u8f66'), ('51', '\u5fae\u578b\u5ba2\u8f66'), ('52', '\u8f7b\u578b\u5ba2\u8f66'), ('53', '\u4e2d\u578b\u5ba2\u8f66'), ('54', '\u5927\u578b\u5ba2\u8f66'), ('55', '\u7279\u5927\u578b\u5ba2\u8f66'), ('61', '\u5fae\u578b\u8f7f\u8f66'), ('62', '\u666e\u901a\u7ea7\u8f7f\u8f66'), ('63', '\u4e2d\u7ea7\u8f7f\u8f66'), ('64', '\u4e2d\u9ad8\u7ea7\u8f7f\u8f66'), ('65', '\u9ad8\u7ea7\u8f7f\u8f66'), ('71', '\u8f7b\u578b\u534a\u6302\u8f66'), ('72', '\u4e2d\u578b\u534a\u6302\u8f66'), ('73', '\u91cd\u578b\u534a\u6302\u8f66'), ('74', '\u8d85\u91cd\u534a\u6302\u8f66'), ('81', '\u6469\u6258\u8f66'), ('82', '\u4e09\u8f6e\u8f66'), ('99', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='99', help_text='\u8be5\u8f66\u8f86\u7684\u8f66\u7ea7\u5206\u7c7b', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='CARGO_BT',
            field=models.CharField(choices=[('0', '\u4e0d\u9002\u7528'), ('1', '\u53a2\u5f0f\u8f66/\u5c01\u95ed\u5f0f\u8f66'), ('2', '\u8d27\u7bb1'), ('3', '\u5e73\u677f\u8f66'), ('4', '\u503e\u5378\u8f66'), ('5', '\u6df7\u6ce5\u571f\u6405\u62cc\u8f66'), ('6', '\u6c7d\u8f66\u8fd0\u9001\u8f66'), ('7', '\u5783\u573e\u8f66'), ('8', '\u8c37\u7269/\u788e\u5757/\u783e\u77f3'), ('9', '\u6746\u62d6\u8f66'), ('10', '\u8f66\u8f86\u7275\u5f15\u53e6\u4e00\u8f86\u8f66'), ('21', '\u5df4\u58eb\uff089-15\u4eba\uff09'), ('22', '\u516c\u5171\u6c7d\u8f66\uff0816\u4eba\u53ca\u4ee5\u4e0a\uff09'), ('23', '\u672a\u77e5\u8d27\u7269\u7c7b\u578b'), ('99', '\u672a\u77e5')], default='0', help_text='\u8be5\u8f66\u8f86\u62c9\u8f7d\u627f\u91cd\u7c7b\u578b', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='HIT_RUN',
            field=models.CharField(choices=[('0', '\u672a\u9003\u9038'), ('1', '\u8087\u4e8b\u9003\u9038'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='9', help_text='\u8087\u4e8b\u9003\u9038\u72b6\u51b5', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='MAKE',
            field=models.CharField(choices=[('01', '\u5927\u4f17'), ('02', '\u5409\u5229'), ('03', '\u672c\u7530'), ('04', '\u5b9d\u9a8f'), ('05', '\u522b\u514b'), ('06', '\u65e5\u4ea7'), ('07', '\u4e30\u7530'), ('08', '\u54c8\u5f17'), ('09', '\u73b0\u4ee3'), ('10', '\u798f\u7279'), ('11', '\u957f\u5b89'), ('12', '\u96ea\u4f5b\u5170'), ('13', '\u4e94\u83f1'), ('14', '\u5965\u8fea'), ('15', '\u8d77\u4e9a'), ('16', '\u6bd4\u4e9a\u8fea'), ('17', '\u4f20\u797a'), ('18', '\u5947\u745e'), ('19', '\u8363\u5a01'), ('20', '\u5b9d\u9a6c'), ('21', '\u4f17\u6cf0'), ('22', '\u5954\u9a70'), ('23', '\u65af\u67ef\u8fbe'), ('24', '\u9a6c\u81ea\u8fbe'), ('25', '\u6807\u81f4'), ('26', '\u94f6\u7fd4'), ('27', '\u4e1c\u98ce\u98ce\u5149'), ('28', '\u4e1c\u98ce\u98ce\u884c'), ('29', '\u957f\u5b89\u5546\u7528'), ('30', '\u6c5f\u6dee'), ('31', 'WEH'), ('32', '\u51ef\u8fea\u62c9\u514b'), ('33', '\u96ea\u94c1\u9f99'), ('34', '\u540d\u7235'), ('35', 'Jeep'), ('36', '\u542f\u8fb0'), ('37', '\u534e\u6cf0'), ('38', '\u5954\u817e'), ('39', '\u540d\u7235'), ('40', '\u7ec5\u5b9d'), ('41', '\u4e00\u6c7d'), ('42', '\u6d77\u9a6c'), ('43', '\u94c3\u6728'), ('44', '\u4e2d\u534e'), ('45', '\u730e\u8c79'), ('46', '\u4e1c\u98ce\u98ce\u795e'), ('47', '\u5f00\u745e'), ('48', '\u5a01\u65fa'), ('49', '\u6bd4\u901f\u6c7d\u8f66'), ('50', '\u6c83\u5c14\u6c83'), ('51', '\u96f7\u514b\u8428\u65af'), ('52', '\u6377\u8c79'), ('53', '\u6797\u80af'), ('54', '\u4fdd\u65f6\u6377'), ('55', 'mini'), ('56', '\u6cd5\u62c9\u5229'), ('57', '\u739b\u838e\u62c9\u8482'), ('58', '\u5170\u535a\u57fa\u5c3c'), ('59', '\u52b3\u65af\u83b1\u65af'), ('60', '\u5bbe\u5229'), ('61', '\u529b\u5e06'), ('62', '\u8def\u864e'), ('63', '\u96f7\u8bfa'), ('64', '\u660c\u6cb3'), ('65', '\u5b9d\u6c83'), ('66', '\u5317\u4eac'), ('67', '\u4e1c\u98ce\u5c0f\u5eb7'), ('68', '\u77e5\u8c46'), ('69', '\u89c2\u81f4'), ('70', '\u51ef\u7ffc'), ('71', '\u91ce\u9a6c'), ('72', '\u7eb3\u667a\u6377'), ('73', '\u82f1\u81f4'), ('74', '\u5eb7\u8fea'), ('75', '\u82f1\u83f2\u5c3c\u8fea'), ('76', '\u798f\u7530'), ('77', '\u91d1\u676f'), ('78', '\u5927\u901a'), ('79', '\u957f\u57ce'), ('80', '\u8bb4\u6b4c'), ('81', '\u4e1c\u98ce\u98ce\u5ea6'), ('82', '\u65b0\u9f99\u9a6c'), ('83', '\u7ea2\u65d7'), ('84', '\u817e\u52bf'), ('85', '\u6c5f\u94c3'), ('86', 'DS'), ('87', '\u5317\u6c7d\u5236\u9020'), ('88', '\u4e1c\u98ce'), ('89', '\u798f\u8fea'), ('90', '\u4e94\u5341\u94c3'), ('91', '\u83f2\u4e9a\u7279'), ('92', '\u534e\u9882'), ('98', '\u5176\u4ed6'), ('99', '\u4e0d\u9002\u7528')], default='99', help_text='\u8be5\u6c7d\u8f66\u54c1\u724c', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='OWNER',
            field=models.CharField(choices=[('0', '\u8f66\u8f86\u672a\u6ce8\u518c'), ('1', '\u9a7e\u9a76\u5458\u662f\u8be5\u8f66\u6ce8\u518c\u4eba'), ('2', '\u9a7e\u9a76\u5458\u4e0d\u662f\u8be5\u8f66\u6ce8\u518c\u4eba'), ('3', '\u6ce8\u518c\u4e3a\u5546\u4e1a/\u516c\u53f8/\u653f\u5e9c\u8f66\u8f86'), ('4', '\u8f66\u8f86\u6ce8\u518c\u4e3a\u79df\u8d41\u8f66\u8f86'), ('5', '\u8be5\u8f66\u88ab\u76d7\uff08\u62a5\u8b66\uff09'), ('6', '\u65e0\u4eba\u9a7e\u9a76/\u505c\u653e\u7684\u673a\u52a8\u8f66'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='9', help_text='\u8fd9\u8f86\u8f66\u6240\u6709\u8005\u7684\u7c7b\u578b', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='PSP_USE',
            field=models.CharField(choices=[('0', '\u65e0\u7279\u6b8a\u7528\u9014'), ('1', '\u51fa\u79df\u8f66'), ('2', '\u6821\u8f66'), ('3', '\u5df4\u58eb'), ('4', '\u519b\u4e8b'), ('5', '\u8b66\u5bdf'), ('6', '\u6551\u62a4\u8f66'), ('7', '\u6d88\u9632\u8f66'), ('99', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='99', help_text='\u8be5\u8f66\u8f86\u662f\u5426\u6709\u4efb\u4f55\u7279\u6b8a\u7528\u9014', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='TOW_VEH',
            field=models.CharField(choices=[('0', '\u65e0\u62d6\u6302\u5355\u4f4d'), ('1', '\u6709\u4e00\u4e2a\u62d6\u6302\u5355\u4f4d'), ('2', '\u6709\u4e24\u4e2a\u62d6\u6302\u5355\u4f4d'), ('3', '\u6709\u4e09\u4e2a\u6216\u4ee5\u4e0a\u62d6\u6302\u5355\u4f4d'), ('4', '\u6709\u672a\u77e5\u62d6\u6302\u5355\u4f4d\u6570'), ('5', '\u4e00\u8f86\u8f66\u7275\u5f15\u53e6\u4e00\u8f86\u8f66-\u56fa\u5b9a\u6746'), ('6', '\u4e00\u8f86\u8f66\u7275\u5f15\u53e6\u4e00\u8f86\u8f66-\u975e\u56fa\u5b9a\u6746'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='9', help_text='\u8be5\u8f66\u8f86\u662f\u5426\u6709\u62d6\u62fd\u5355\u4f4d\u6216\u8005\u8f66\u8f86', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='UNTYPE',
            field=models.CharField(choices=[('1', '\u5728\u9053\u8def\u4e0a\u8fd0\u8f93\u4e2d\u7684\u8f66\u8f86'), ('2', '\u5728\u9053\u8def\u5916'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='9', help_text='\u8f66\u8f86\u72b6\u51b5\u4fe1\u606f', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='decription',
            field=models.CharField(default='Accident.NAME\u6d89\u4e8b\u8f66\u8f86\u72b6\u51b5', max_length=30),
        ),
    ]
