# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0005_auto_20180112_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(default='/images/\u521a\u5ea6\u7cfb\u6570.PNG'),
        ),
    ]
