# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0007_auto_20180119_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='NAME',
            field=models.CharField(auto_created='CITY', default='xxxxxx xxxx', help_text='\u6848\u4ef6\u7f16\u7801', max_length=30),
        ),
    ]
