# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0010_auto_20180119_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='CITY',
            field=models.CharField(default='000000', help_text='\u884c\u653f\u533a\u5212\u5206\u4ee3\u7801', max_length=10),
        ),
    ]
