# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0011_auto_20180119_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledata',
            name='decription',
        ),
        migrations.AddField(
            model_name='vehicledata',
            name='NAME',
            field=models.CharField(default='\u70b9\u51fb\u4fdd\u5b58\u65f6\u4f1a\u81ea\u52a8\u7f16\u7801', help_text='\u8f66\u8f86\u7f16\u7801', max_length=30),
        ),
        migrations.AlterField(
            model_name='accident',
            name='NAME',
            field=models.CharField(default='\u70b9\u51fb\u4fdd\u5b58\u65f6\u4f1a\u81ea\u52a8\u7f16\u7801', help_text='\u6848\u4ef6\u7f16\u7801', max_length=30),
        ),
        migrations.AlterField(
            model_name='accident',
            name='NUM',
            field=models.CharField(default='0001', help_text='\u5730\u533a\u6848\u4ef6\u7f16\u53f7,4\u4f4d\u6570', max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='VEH_NO',
            field=models.CharField(default=0, help_text='\u4e8b\u6545\u8f66\u8f86\u7f16\u53f7\uff0c\u884c\u4eba\u4e3a00,2\u4f4d\u6570', max_length=5),
        ),
    ]
