# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0012_auto_20180119_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='persondata',
            name='NAME',
            field=models.CharField(default='\u70b9\u51fb\u4fdd\u5b58\u65f6\u4f1a\u81ea\u52a8\u7f16\u7801', help_text='\u4eba\u5458\u7f16\u7801', max_length=30),
        ),
        migrations.AddField(
            model_name='photo',
            name='NAME',
            field=models.CharField(default='\u70b9\u51fb\u4fdd\u5b58\u65f6\u4f1a\u81ea\u52a8\u547d\u540d', max_length=20),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='PER_NO',
            field=models.CharField(default=1, help_text='\u8be5\u4eba\u5458\u7f16\u53f7\uff0c\u884c\u4eba\u4e0e\u4e58\u5458\uff08\u542b\u9a7e\u9a76\u5458\uff09\u5206\u5f00\u7f16\u7801', max_length=10),
        ),
    ]
