# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0014_auto_20180119_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='SFATOR1',
            field=models.CharField(choices=[('0', '\u65e0'), ('1', '\u51fa\u53e3\u8b66\u793a'), ('2', '\u8def\u80a9\u76f8\u5173'), ('3', '\u5176\u4ed6\u7ef4\u62a4\u6216\u5efa\u9020'), ('4', '\u6ca1\u6709\u6216\u6a21\u7cca\u7684\u8def\u9762\u6807\u8bb0'), ('5', '\u5730\u8868\u6709\u79ef\u6c34'), ('6', '\u9053\u8def\u6865\u6881\u7b49\u65bd\u5de5\u6216\u8bbe\u8ba1\u7f3a\u9677'), ('7', '\u8868\u9762\u51b2\u6d17\uff08\u584c\u9677\u8def\u6ed1\uff09'), ('8', '\u975e\u63a5\u89e6\u9a7e\u9a76\u5458\u7684\u4fb5\u72af-\u8def\u6012'), ('9', '\u975e\u673a\u52a8\u8f66\u4eba\u5458\u88ab\u6389\u843d\u8d27\u7269\u649e\u51fb'), ('10', '\u975e\u673a\u52a8\u8f66\u4eba\u5458\u649e\u51fb\u6c7d\u8f66'), ('11', '\u8fd0\u52a8\u4e2d\u7684\u8f66\u8f86\u629b\u843d\u4e58\u5ba2'), ('12', '\u6d89\u53ca\u8b66\u65b9\u8ffd\u6355'), ('13', '\u62a5\u5e9f\u8f66\u8f86'), ('14', '\u9053\u8def\u4e4b\u5916\u6709\u4e8b\u60c5\u53d1\u751f'), ('15', '\u5e7f\u573a\u505c\u8f66\u573a\u76f8\u5173'), ('16', '\u672a\u77e5')], default='0', help_text='\u73b0\u573a\u52d8\u67e5\u72b6\u51b5\uff0c\u6700\u591a4\u9879', max_length=20),
        ),
        migrations.AddField(
            model_name='accident',
            name='SFATOR2',
            field=models.CharField(choices=[('0', '\u65e0'), ('1', '\u51fa\u53e3\u8b66\u793a'), ('2', '\u8def\u80a9\u76f8\u5173'), ('3', '\u5176\u4ed6\u7ef4\u62a4\u6216\u5efa\u9020'), ('4', '\u6ca1\u6709\u6216\u6a21\u7cca\u7684\u8def\u9762\u6807\u8bb0'), ('5', '\u5730\u8868\u6709\u79ef\u6c34'), ('6', '\u9053\u8def\u6865\u6881\u7b49\u65bd\u5de5\u6216\u8bbe\u8ba1\u7f3a\u9677'), ('7', '\u8868\u9762\u51b2\u6d17\uff08\u584c\u9677\u8def\u6ed1\uff09'), ('8', '\u975e\u63a5\u89e6\u9a7e\u9a76\u5458\u7684\u4fb5\u72af-\u8def\u6012'), ('9', '\u975e\u673a\u52a8\u8f66\u4eba\u5458\u88ab\u6389\u843d\u8d27\u7269\u649e\u51fb'), ('10', '\u975e\u673a\u52a8\u8f66\u4eba\u5458\u649e\u51fb\u6c7d\u8f66'), ('11', '\u8fd0\u52a8\u4e2d\u7684\u8f66\u8f86\u629b\u843d\u4e58\u5ba2'), ('12', '\u6d89\u53ca\u8b66\u65b9\u8ffd\u6355'), ('13', '\u62a5\u5e9f\u8f66\u8f86'), ('14', '\u9053\u8def\u4e4b\u5916\u6709\u4e8b\u60c5\u53d1\u751f'), ('15', '\u5e7f\u573a\u505c\u8f66\u573a\u76f8\u5173'), ('16', '\u672a\u77e5')], default='0', help_text='\u73b0\u573a\u52d8\u67e5\u72b6\u51b5\uff0c\u6700\u591a4\u9879', max_length=20),
        ),
        migrations.AddField(
            model_name='accident',
            name='SFATOR3',
            field=models.CharField(choices=[('0', '\u65e0'), ('1', '\u51fa\u53e3\u8b66\u793a'), ('2', '\u8def\u80a9\u76f8\u5173'), ('3', '\u5176\u4ed6\u7ef4\u62a4\u6216\u5efa\u9020'), ('4', '\u6ca1\u6709\u6216\u6a21\u7cca\u7684\u8def\u9762\u6807\u8bb0'), ('5', '\u5730\u8868\u6709\u79ef\u6c34'), ('6', '\u9053\u8def\u6865\u6881\u7b49\u65bd\u5de5\u6216\u8bbe\u8ba1\u7f3a\u9677'), ('7', '\u8868\u9762\u51b2\u6d17\uff08\u584c\u9677\u8def\u6ed1\uff09'), ('8', '\u975e\u63a5\u89e6\u9a7e\u9a76\u5458\u7684\u4fb5\u72af-\u8def\u6012'), ('9', '\u975e\u673a\u52a8\u8f66\u4eba\u5458\u88ab\u6389\u843d\u8d27\u7269\u649e\u51fb'), ('10', '\u975e\u673a\u52a8\u8f66\u4eba\u5458\u649e\u51fb\u6c7d\u8f66'), ('11', '\u8fd0\u52a8\u4e2d\u7684\u8f66\u8f86\u629b\u843d\u4e58\u5ba2'), ('12', '\u6d89\u53ca\u8b66\u65b9\u8ffd\u6355'), ('13', '\u62a5\u5e9f\u8f66\u8f86'), ('14', '\u9053\u8def\u4e4b\u5916\u6709\u4e8b\u60c5\u53d1\u751f'), ('15', '\u5e7f\u573a\u505c\u8f66\u573a\u76f8\u5173'), ('16', '\u672a\u77e5')], default='0', help_text='\u73b0\u573a\u52d8\u67e5\u72b6\u51b5\uff0c\u6700\u591a4\u9879', max_length=20),
        ),
        migrations.AddField(
            model_name='persondata',
            name='ABDOMEN_HURT',
            field=models.CharField(choices=[('0', '\u672a\u53d7\u4f24'), ('1', '\u53d7\u4f24'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u8179\u90e8\u662f\u5426\u53d7\u4f24', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='CHEST_HURT',
            field=models.CharField(choices=[('0', '\u672a\u53d7\u4f24'), ('1', '\u53d7\u4f24'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u80f8\u90e8\u662f\u5426\u53d7\u4f24', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='DEATH',
            field=models.CharField(choices=[('1', '\u6b7b\u4ea1'), ('2', '\u53d7\u4f24'), ('3', '\u672a\u53d7\u4f24'), ('9', '\u672a\u77e5')], default='1', help_text='\u8be5\u4eba\u5458\u662f\u5426\u6b7b\u4ea1', max_length=10),
        ),
        migrations.AddField(
            model_name='persondata',
            name='DREASON',
            field=models.CharField(choices=[('1', '\u5934\u90e8'), ('2', '\u80f8\u90e8'), ('3', '\u8179\u90e8'), ('4', '\u7efc\u5408'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='9', help_text='\u8eab\u4f53\u54ea\u4e2a\u90e8\u4f4d\u521b\u4f24\u5bfc\u81f4\u6b7b\u4ea1', max_length=10),
        ),
        migrations.AddField(
            model_name='persondata',
            name='FRACTURE',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='FRACTURE1',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='FRACTURE2',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='FRACTURE3',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='FRACTURE4',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='FRACTURE5',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='FRACTURE6',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='HARNPAN1',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='HARNPAN2',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='HARNPAN3',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='HARNPAN4',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='HARNPAN5',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='HARNPAN6',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='HEAD_HURT',
            field=models.CharField(choices=[('0', '\u672a\u53d7\u4f24'), ('1', '\u53d7\u4f24'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u5934\u90e8\u662f\u5426\u53d7\u4f24', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='HEIGHT',
            field=models.PositiveIntegerField(default=0, help_text='\u8be5\u4eba\u5458\u8eab\u9ad8\uff0ccm', max_length=5),
        ),
        migrations.AddField(
            model_name='persondata',
            name='IN_HEMORRHAGE1',
            field=models.CharField(choices=[('0', '\u672a\u51fa\u8840'), ('1', '\u786c\u819c\u4e0b\u8154'), ('2', '\u86db\u7f51\u819c\u4e0b\u8154'), ('3', '\u8111'), ('4', '\u786c\u819c\u5916'), ('5', '\u8111\u632b\u88c2\u4f24'), ('6', '\u8111\u5ba4\u5185'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u5185\u51fa\u8840', max_length=10),
        ),
        migrations.AddField(
            model_name='persondata',
            name='IN_HEMORRHAGE2',
            field=models.CharField(choices=[('0', '\u672a\u51fa\u8840'), ('1', '\u786c\u819c\u4e0b\u8154'), ('2', '\u86db\u7f51\u819c\u4e0b\u8154'), ('3', '\u8111'), ('4', '\u786c\u819c\u5916'), ('5', '\u8111\u632b\u88c2\u4f24'), ('6', '\u8111\u5ba4\u5185'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u5185\u51fa\u8840', max_length=10),
        ),
        migrations.AddField(
            model_name='persondata',
            name='IN_HEMORRHAGE3',
            field=models.CharField(choices=[('0', '\u672a\u51fa\u8840'), ('1', '\u786c\u819c\u4e0b\u8154'), ('2', '\u86db\u7f51\u819c\u4e0b\u8154'), ('3', '\u8111'), ('4', '\u786c\u819c\u5916'), ('5', '\u8111\u632b\u88c2\u4f24'), ('6', '\u8111\u5ba4\u5185'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u5185\u51fa\u8840', max_length=10),
        ),
        migrations.AddField(
            model_name='persondata',
            name='IN_HEMORRHAGE4',
            field=models.CharField(choices=[('0', '\u672a\u51fa\u8840'), ('1', '\u786c\u819c\u4e0b\u8154'), ('2', '\u86db\u7f51\u819c\u4e0b\u8154'), ('3', '\u8111'), ('4', '\u786c\u819c\u5916'), ('5', '\u8111\u632b\u88c2\u4f24'), ('6', '\u8111\u5ba4\u5185'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u5185\u51fa\u8840', max_length=10),
        ),
        migrations.AddField(
            model_name='persondata',
            name='IN_HEMORRHAGE5',
            field=models.CharField(choices=[('0', '\u672a\u51fa\u8840'), ('1', '\u786c\u819c\u4e0b\u8154'), ('2', '\u86db\u7f51\u819c\u4e0b\u8154'), ('3', '\u8111'), ('4', '\u786c\u819c\u5916'), ('5', '\u8111\u632b\u88c2\u4f24'), ('6', '\u8111\u5ba4\u5185'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u5185\u51fa\u8840', max_length=10),
        ),
        migrations.AddField(
            model_name='persondata',
            name='IN_HEMORRHAGE6',
            field=models.CharField(choices=[('0', '\u672a\u51fa\u8840'), ('1', '\u786c\u819c\u4e0b\u8154'), ('2', '\u86db\u7f51\u819c\u4e0b\u8154'), ('3', '\u8111'), ('4', '\u786c\u819c\u5916'), ('5', '\u8111\u632b\u88c2\u4f24'), ('6', '\u8111\u5ba4\u5185'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u5185\u51fa\u8840', max_length=10),
        ),
        migrations.AddField(
            model_name='persondata',
            name='LEGS_HURT',
            field=models.CharField(choices=[('0', '\u672a\u53d7\u4f24'), ('1', '\u53d7\u4f24'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u4e0b\u80a2\u662f\u5426\u53d7\u4f24', max_length=5),
        ),
        migrations.AlterField(
            model_name='accident',
            name='SFACTOR',
            field=models.CharField(choices=[('0', '\u65e0'), ('1', '\u51fa\u53e3\u8b66\u793a'), ('2', '\u8def\u80a9\u76f8\u5173'), ('3', '\u5176\u4ed6\u7ef4\u62a4\u6216\u5efa\u9020'), ('4', '\u6ca1\u6709\u6216\u6a21\u7cca\u7684\u8def\u9762\u6807\u8bb0'), ('5', '\u5730\u8868\u6709\u79ef\u6c34'), ('6', '\u9053\u8def\u6865\u6881\u7b49\u65bd\u5de5\u6216\u8bbe\u8ba1\u7f3a\u9677'), ('7', '\u8868\u9762\u51b2\u6d17\uff08\u584c\u9677\u8def\u6ed1\uff09'), ('8', '\u975e\u63a5\u89e6\u9a7e\u9a76\u5458\u7684\u4fb5\u72af-\u8def\u6012'), ('9', '\u975e\u673a\u52a8\u8f66\u4eba\u5458\u88ab\u6389\u843d\u8d27\u7269\u649e\u51fb'), ('10', '\u975e\u673a\u52a8\u8f66\u4eba\u5458\u649e\u51fb\u6c7d\u8f66'), ('11', '\u8fd0\u52a8\u4e2d\u7684\u8f66\u8f86\u629b\u843d\u4e58\u5ba2'), ('12', '\u6d89\u53ca\u8b66\u65b9\u8ffd\u6355'), ('13', '\u62a5\u5e9f\u8f66\u8f86'), ('14', '\u9053\u8def\u4e4b\u5916\u6709\u4e8b\u60c5\u53d1\u751f'), ('15', '\u5e7f\u573a\u505c\u8f66\u573a\u76f8\u5173'), ('16', '\u672a\u77e5')], default='0', help_text='\u73b0\u573a\u52d8\u67e5\u72b6\u51b5\uff0c\u6700\u591a4\u9879', max_length=20),
        ),
    ]
