# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0015_auto_20180122_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='HEIGHT',
            field=models.PositiveIntegerField(default=0, help_text='\u8be5\u4eba\u5458\u8eab\u9ad8\uff0ccm'),
        ),
    ]
