# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0016_auto_20180122_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='VEDIO',
            field=models.CharField(choices=[('0', '\u65e0\u89c6\u9891'), ('1', '\u56fa\u5b9a\u5f0f\u76d1\u63a7\u5f55\u50cf'), ('2', '\u884c\u8f66\u8bb0\u5f55\u4eea'), ('8', '\u5176\u4ed6\u89c6\u9891\u8bb0\u5f55\u8bbe\u5907'), ('9', '\u672a\u77e5')], default='0', help_text='\u8bb0\u5f55\u6b64\u6848\u4ef6\u6216\u4e0e\u6b64\u6848\u4ef6\u76f8\u5173\u7684\u89c6\u9891', max_length=15),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='HARNPAN1',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('7', '\u9aa8\u6298\uff0c\u672a\u77e5\u4f4d\u7f6e'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='HARNPAN2',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('7', '\u9aa8\u6298\uff0c\u672a\u77e5\u4f4d\u7f6e'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='HARNPAN3',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('7', '\u9aa8\u6298\uff0c\u672a\u77e5\u4f4d\u7f6e'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='HARNPAN4',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('7', '\u9aa8\u6298\uff0c\u672a\u77e5\u4f4d\u7f6e'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='HARNPAN5',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('7', '\u9aa8\u6298\uff0c\u672a\u77e5\u4f4d\u7f6e'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='HARNPAN6',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u989e\u9aa8'), ('2', '\u6795\u9aa8'), ('3', '\u9876\u9aa8'), ('4', '\u989d\u9aa8'), ('5', '\u8776\u9aa8'), ('6', '\u9885\u5e95'), ('7', '\u9aa8\u6298\uff0c\u672a\u77e5\u4f4d\u7f6e'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='0', help_text='\u9885\u9aa8\u9aa8\u6298', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='HEIGHT',
            field=models.CharField(default=999, help_text='\u8be5\u4eba\u5458\u8eab\u9ad8cm,999\u672a\u77e5', max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='P_CRASH2',
            field=models.CharField(choices=[('0', '\u65e0\u9a7e\u9a76\u5458/\u672a\u77e5\u9a7e\u9a76\u5458\u662f\u5426\u5b58\u5728'), ('1', '\u7559\u4e0b\u75d5\u8ff9'), ('2', '\u7eb5\u5411\u65cb\u8f6c\u5c0f\u9c7c30\xb0'), ('3', '\u4fa7\u6ed1-\u9006\u65f6\u9488\u65cb\u8f6c'), ('4', '\u4fa7\u6ed1-\u987a\u65f6\u9488\u65cb\u8f6c'), ('5', '\u5176\u4ed6\u8f66\u8f86\u5931\u63a7'), ('6', '\u7a33\u5b9a'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='9', help_text='\u8be5\u8f66\u8f86\u5728\u4e8b\u6545\u524d\u7684\u7a33\u5b9a\u6027', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='TRAV_SP',
            field=models.CharField(default=0, help_text='\u4e8b\u53d1\u524d\u8be5\u8f66\u901f\u5ea6km/h,999\u672a\u77e5', max_length=5),
        ),
    ]
