# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0018_auto_20180123_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='DAY_WEEK',
            field=models.CharField(choices=[('0', '\u672a\u77e5'), ('1', '\u661f\u671f\u4e00'), ('2', '\u661f\u671f\u4e8c'), ('3', '\u661f\u671f\u4e09'), ('4', '\u661f\u671f\u56db'), ('5', '\u661f\u671f\u4e94'), ('6', '\u661f\u671f\u516d'), ('7', '\u661f\u671f\u65e5')], default='\u661f\u671f\u4e00', help_text='\u4e8b\u53d1\u662f\u5468\u51e0', max_length=10),
        ),
    ]
