# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0030_auto_20180305_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='FRACTURE',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('8', '\u9888\u90e8'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='FRACTURE1',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('8', '\u9888\u90e8'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='FRACTURE2',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('8', '\u9888\u90e8'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='FRACTURE3',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('8', '\u9888\u90e8'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='FRACTURE4',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('8', '\u9888\u90e8'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='FRACTURE5',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('8', '\u9888\u90e8'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='FRACTURE6',
            field=models.CharField(choices=[('0', '\u672a\u9aa8\u6298'), ('1', '\u808b\u9aa8'), ('2', '\u80f8\u9aa8'), ('3', '\u76c6\u9aa8'), ('4', '\u9762\u90e8'), ('5', '\u4e0a\u80a2\u9aa8'), ('6', '\u4e0b\u80a2\u9aa8'), ('7', '\u810a\u67f1'), ('8', '\u9888\u90e8'), ('9', '\u672a\u77e5/\u4e0d\u53ef\u7528')], default='0', help_text='\u9aa8\u6298\u90e8\u4f4d', max_length=5),
        ),
    ]
