# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-06 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0036_auto_20180306_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='ALC_RES',
            field=models.PositiveIntegerField(default=999, help_text='\u9152\u7cbe\u6d4b\u8bd5\u7ed3\u679cmg/100ml\uff08\u5439\u6c14/\u8840\u68c0\uff09\uff0c999\u672a\u77e5'),
        ),
    ]
