# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0038_auto_20180306_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='L_TYPE',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('M', 'M'), ('N', 'N'), ('NON', '\u672a\u83b7\u5f97\u9a7e\u9a76\u8bc1'), ('O', '\u4e0d\u9002\u7528')], default='O', help_text='\u8be5\u8f66\u9a7e\u9a76\u5458\u9a7e\u9a76\u8bc1\u7ea7\u522b', max_length=10),
        ),
    ]
