# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrash', '0039_auto_20180307_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='P_CRASH2',
            field=models.CharField(choices=[('0', '\u65e0\u9a7e\u9a76\u5458/\u672a\u77e5\u9a7e\u9a76\u5458\u662f\u5426\u5b58\u5728'), ('1', '\u7559\u4e0b\u75d5\u8ff9'), ('2', '\u7eb5\u5411\u65cb\u8f6c\u5c0f\u4e8e30\xb0'), ('3', '\u4fa7\u6ed1-\u9006\u65f6\u9488\u65cb\u8f6c'), ('4', '\u4fa7\u6ed1-\u987a\u65f6\u9488\u65cb\u8f6c'), ('5', '\u7ffb\u8f6c'), ('6', '\u7a33\u5b9a'), ('7', '\u5176\u4ed6\u5931\u63a7'), ('9', '\u672a\u77e5/\u4e0d\u9002\u7528')], default='9', help_text='\u8be5\u8f66\u8f86\u5728\u4e8b\u6545\u524d\u7684\u7a33\u5b9a\u6027', max_length=15),
        ),
    ]
